### ISSUE TITLE
LetTerm

### ISSUE THREAD

**Issue by garganti** [uasm/language-definiton#7]
we need a LetTerm. We would add a new Term defined as follows:
LetTerm: 
'let' varTerm+=VariableTerm '=' term+=Term (',' varTerm+=VariableTerm '=' term+=Term)\* 'in' body=Term;

**Comment by garganti** [comment]
BasicTerm:
    (LocationTerm | ConditionalTerm | CaseTerm | ForAllTerm | ExistsTerm | LetTerm | ComprehensionTerm | StructureTerm | PickTerm  | RuleAsTerm | ReturnTerm | Literal | TupleLiteral);

**Comment by mstegmaier** [comment]
That's the ReturnTerm just that the ReturnTerm doesn't support multiple variables, (yet).

**Comment by garganti** [comment]
I don't know how to use the ReturnTerm but I doubt it fits our need. We would like to introduce a new locally scoped variable (like x = y + 10) and build a term depending on x (like x_x). Something like:
let x = y + 10 in x *x, would return  (y +10)_ (y+10).

**Comment by mstegmaier** [comment]
Can you provide more context of your usecase?

If you have
`someFunction := (y + 10) * (y + 10)`
you want to write it as
`someFunction := let x = y + 10 in x * x`
how is that better than using the LetRule (see below)?
`let x = y + 10 in someFunction := x * x`

Similarly if you have
`Rule((y + 10) * (y + 10))`
you want to write
`Rule(let x = y + 10 in x * x)`
but you could also write
`let x = y + 10 in Rule(x * x)`

Do you have any example where a LetTerm would have an advantage over the LetRule?

Regarding the ReturnTerm, it can be used to calculate more complex terms using a rule.
For example you could do

```
derived palindrome(inputList) := return list in seq
  list := []
  while |inputList| > 0 do par
    list := [head(inputList)] + list + [head(inputList)]
    inputList := tail(inputList)
  endpar
endseq
```

**Comment by silviabonfanti** [comment]
An example is the inizialization of static or derived funcition.
InitialFunctionDefinition requires Term, so we cannot use Rule.

For this reason if we want to inizialize a static function as (y +10) (y+10), it is a Term and not a Rule.

**Comment by mstegmaier** [comment]
Ah, there we have another example showing that there is no need for a LetTerm. How about the others? Do you also agree that we don't need a LetTerm?

**Comment by silviabonfanti** [comment]
No no, we need LetTerm otherwise the example doesn't work.
Because if we want to use a variable x=(y+10) and write x*x instead of (y+10)(y+10) we need LetTerm

**Comment by mstegmaier** [comment]
Oh, sorry, then I misunderstood your previous comment.
You were talking about Rules while there wasn't any need for Rules in your example.

So your example is as follows?:
`derived derivedFunction(y) = let x = y + 10 in x * x`
what keeps you from writing the following?:
`derived derivedFunction(y) = (y + 10) * (y + 10)`

For more complex calculations you can always use the ReturnTerm to return the value computed by a rule (as seen in the example in my previous comment).

With the ReturnTerm you could also write the following:
`derived derivedFunction(y) = return x * x in x := y + 10`

**Comment by garganti** [comment]
We are not very familiar with the return term, which we do not understand exactly yet, but we will figure out how it works hopefully soon (maybe we will need some help here). 
We'd prefer to avoid the use of rules (as in the return term) when defining terms as much as possible (sometimes it is not possible and the return term is necessary).
About the letterm, if we mean "necessary" as it increases the expressive power, it is true that the letterm is not necessary, but also the letrule is not necessary either. 
So the letterm is _useful_ when one wants to have a compact representation of terms.
For instance in
`derived derivedFunction(y) = let x = complexTerm in x + x * x`
it is true that one could write: 
`derived derivedFunction(y) =  complexTerm + complexTerm * complexTerm`
but it is:
- more difficult to write (so error prone during modeling) and read
- more difficult to maintain (once I want to change complexTerm definition, without let I have to change its definition in many places)
- more difficult to interpret (the simulator has to evaluate complexTerm several times)

For these reasons, we still propose to have a letTerm.

**Comment by silviabonfanti** [comment]
As agreed during ABZ2016 conference LetTerm is inserted into the grammar as optional.
This term is supported by ASMETA and not by CoreASM.
